version: 0.0
os: linux

files:
  - source: files/nginx.conf
    destination: /etc/nginx/
  - source: files/staticserver.js
    destination: /usr/share/nginx/html/
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 120
  AfterInstall:
    - location: scripts/start.sh
      timeout: 120
